<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Instructions</name>
   <tag></tag>
   <elementGuidId>d97b85a6-3781-44f3-9ad3-fcca950a585e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='block-cet']/div/ul/li[7]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Instructions &quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1316babe-2374-470d-9c78-6a8368152d00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/293/cet-instructions</value>
      <webElementGuid>7591aace-0d1f-4f94-90c2-5fa69da2974c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gva_layout</name>
      <type>Main</type>
      <value>menu-list</value>
      <webElementGuid>d197aa17-e5e2-47a1-ac30-482490d23762</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gva_layout_columns</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>a764d82c-ed37-41cc-a4a8-d471347603e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gva_block</name>
      <type>Main</type>
      <value>23escmm</value>
      <webElementGuid>6164d2e5-121f-418c-b136-d58765dfc8fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gva_block_en</name>
      <type>Main</type>
      <value>23escmm</value>
      <webElementGuid>f026eee4-5291-43e6-aaa9-5b41733f006c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gva_block_ta</name>
      <type>Main</type>
      <value>23escmm</value>
      <webElementGuid>ac62877e-3f6a-48e8-a210-3f5129759d9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-drupal-link-system-path</name>
      <type>Main</type>
      <value>node/3361</value>
      <webElementGuid>cf748467-129b-46c0-acda-bdd9ebfd670f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Instructions</value>
      <webElementGuid>fc5f4e85-4b17-4197-acf2-d57173d3bf25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;block-cet&quot;)/div[@class=&quot;block-content&quot;]/ul[@class=&quot;gva_menu&quot;]/li[@class=&quot;menu-item&quot;]/a[1]</value>
      <webElementGuid>5df4f348-8e4a-4595-b3a5-22fe62632919</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='block-cet']/div/ul/li[7]/a</value>
      <webElementGuid>59bb8396-b0cc-4920-93d5-b3a883aff905</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Instructions')]</value>
      <webElementGuid>840bc0ab-20f5-48d1-a116-9627b6765fef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Guidelines'])[1]/following::a[1]</value>
      <webElementGuid>e21cc769-df05-49b9-80b8-b20e7d33edf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact'])[1]/following::a[2]</value>
      <webElementGuid>d1501359-c43a-4fb7-aadd-a944f6c7990b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Online Registration'])[1]/preceding::a[1]</value>
      <webElementGuid>87f3bab6-ae1d-41ee-8103-873cd22e2fd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CET Guidelines'])[1]/preceding::a[2]</value>
      <webElementGuid>b6e9471c-7eb8-4745-bcae-936f5edd5ef0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Instructions']/parent::*</value>
      <webElementGuid>0ea8a71f-80b5-481c-b512-4671993c0522</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/293/cet-instructions')]</value>
      <webElementGuid>e5e36917-2c72-4cb5-97f5-a664f4fbe2af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div/ul/li[7]/a</value>
      <webElementGuid>98a0ea64-e231-41a5-bd10-42be029baf58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/293/cet-instructions' and (text() = 'Instructions' or . = 'Instructions')]</value>
      <webElementGuid>e3df7996-e296-481e-a873-d535c7ee4216</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
