<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Online Registration</name>
   <tag></tag>
   <elementGuidId>91921750-b44c-4737-8bb5-d7b5b4d687ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='block-cet']/div/ul/li[8]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Online Registration &quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a6b00856-b6e7-413f-a0b6-a688cbab44eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://fms.b-u.ac.in/cet/</value>
      <webElementGuid>ef1ec1c3-ccfd-4bbc-8035-f491e6707d47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gva_layout</name>
      <type>Main</type>
      <value>menu-list</value>
      <webElementGuid>8575a56b-a532-4468-ae5d-85ee77d75d33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gva_layout_columns</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>768e2dcf-ef84-4bbd-90a8-eabc5ed3d1e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gva_block</name>
      <type>Main</type>
      <value>23escmm</value>
      <webElementGuid>df1f2415-173b-4139-bd19-2c86ef45be49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gva_block_en</name>
      <type>Main</type>
      <value>23escmm</value>
      <webElementGuid>b86e4afa-b196-459b-8385-29fa8fed86ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gva_block_ta</name>
      <type>Main</type>
      <value>23escmm</value>
      <webElementGuid>6a2f85d1-028a-45a4-9f5e-dbf5fb891ad6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Online Registration</value>
      <webElementGuid>4dff221c-ea4f-4080-8446-1bb74bc64b9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;block-cet&quot;)/div[@class=&quot;block-content&quot;]/ul[@class=&quot;gva_menu&quot;]/li[@class=&quot;menu-item&quot;]/a[1]</value>
      <webElementGuid>4321484d-07c7-4e6e-9891-448b09853aca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='block-cet']/div/ul/li[8]/a</value>
      <webElementGuid>cb2b7414-4921-447d-b138-ccf0ebf6d695</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Online Registration')]</value>
      <webElementGuid>cb6d5c58-e5ac-49cc-bfbc-5b6e8acbbe7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Instructions'])[1]/following::a[1]</value>
      <webElementGuid>f6b42c5b-e864-4776-9ba0-87afb3463ac3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Guidelines'])[1]/following::a[2]</value>
      <webElementGuid>1a44d2f8-1315-4131-b27a-c9b89f37b080</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CET Instructions'])[1]/preceding::a[1]</value>
      <webElementGuid>404a13da-1efb-4fe1-9fcb-831cbb400ae7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Campus Walk'])[1]/preceding::a[1]</value>
      <webElementGuid>63fc3276-72a9-47f5-aef9-224624c4166b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Online Registration']/parent::*</value>
      <webElementGuid>93ea6d75-cce5-4fe3-8b9e-19ca0b2dcd50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://fms.b-u.ac.in/cet/')])[2]</value>
      <webElementGuid>3d50757a-9df5-4f4e-bfde-735c86395645</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div/ul/li[8]/a</value>
      <webElementGuid>a4b069fa-189c-4eca-a95b-f161d3e20db6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://fms.b-u.ac.in/cet/' and (text() = 'Online Registration' or . = 'Online Registration')]</value>
      <webElementGuid>180c475c-b238-4b03-8424-87930c574389</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
