<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Pay_1</name>
   <tag></tag>
   <elementGuidId>3e4dfffe-04e5-40e3-bc36-987f4e9174e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='services']/div[2]/ul/li[6]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>li >> internal:has-text=&quot;Various Fees &amp; General Remittance Pay&quot;i >> internal:role=link</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1af102c3-8cbb-45e1-9a9b-69344be8fd05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://fms.b-u.ac.in/various-fees/</value>
      <webElementGuid>db93198d-b654-4554-8a49-038d22131bf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pay</value>
      <webElementGuid>09cc883e-9ee7-4fbb-9efd-91357f42d7da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;services&quot;)/div[@class=&quot;content1&quot;]/ul[@class=&quot;cards&quot;]/li[@class=&quot;card&quot;]/div[@class=&quot;text&quot;]/a[1]</value>
      <webElementGuid>bdef3ed1-9c82-4fc3-af75-bb3d5cfce964</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='services']/div[2]/ul/li[6]/div/a</value>
      <webElementGuid>0b8433c2-12e4-41c9-91cc-572ed642a2a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Pay')])[2]</value>
      <webElementGuid>28c291ad-feae-4e1f-9665-ea9b1efb0f47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Various Fees &amp; General Remittance'])[1]/following::a[1]</value>
      <webElementGuid>08e7d726-3541-4093-bb42-e6ca5a0e64f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pay'])[1]/following::a[1]</value>
      <webElementGuid>239b5c59-a20d-4df5-865c-e1326d5f4fc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rent'])[1]/preceding::a[1]</value>
      <webElementGuid>0f3c02ea-ccf3-49d7-a162-8f4a59c9fc43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remittance'])[1]/preceding::a[1]</value>
      <webElementGuid>65e21a8a-54ce-47fa-a18a-d3fb991e920c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://fms.b-u.ac.in/various-fees/')]</value>
      <webElementGuid>cb8aacba-6cb6-4977-aa3f-d669be574547</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/div/a</value>
      <webElementGuid>d0b0cb5b-e15f-4dad-b350-58c32b268203</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://fms.b-u.ac.in/various-fees/' and (text() = 'Pay' or . = 'Pay')]</value>
      <webElementGuid>0f06b3d5-8bed-418d-9731-efecf44d679e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
