<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Institution Login_email_id</name>
   <tag></tag>
   <elementGuidId>0c774800-3f04-4f09-900c-3d17e75a2179</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_email_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_email_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Enter Email Id&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a44aaa91-da75-4a88-a088-af52a631fb2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>05778e00-f8e9-4341-9542-66c1f0440128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email_id</value>
      <webElementGuid>be7ffcc8-4022-476d-8833-58357edba0e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>281f5e1c-9f3b-4a2c-9320-61ce939673f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Email Id</value>
      <webElementGuid>0143978e-ced8-4a03-859d-0240f64fa78f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_email_id</value>
      <webElementGuid>2426b1dc-8ba1-46f7-94dd-b1d562bebca5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_email_id&quot;)</value>
      <webElementGuid>f3f2fada-b38c-4e45-9b45-f10797813fd1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_email_id']</value>
      <webElementGuid>34f9a1dc-a771-47d6-91fa-ffd1fb81aa05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>24253bcc-eede-43e9-9751-8e26d166d042</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'email_id' and @placeholder = 'Enter Email Id' and @id = 'id_email_id']</value>
      <webElementGuid>980d1745-51e9-41e7-990e-110e96b863c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
