<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Forgot Password_submit</name>
   <tag></tag>
   <elementGuidId>f17bb23c-3cd3-46de-b4be-5bd1d77ed193</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-xs-4.pull-right > input[name=&quot;submit&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='submit'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Login&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d46b3f0a-01a5-4a0f-af65-7db0622eb081</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-bordred btn-block waves-effect waves-light text-uppercase document-button</value>
      <webElementGuid>5b629e07-39e4-4096-a078-4522058298bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>a2dba763-4ea6-4fe8-9c42-da89843a8da9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>aa80b249-bb3a-4340-9495-da39048ba1e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>227e1cb9-cb7e-4071-ba5f-9a12678a049d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;stab&quot;)/div[@class=&quot;resp-tabs-container hor_1&quot;]/div[@class=&quot;resp-tab-content hor_1 resp-tab-content-active&quot;]/div[1]/div[@class=&quot;wrapper-page&quot;]/form[1]/div[@class=&quot;m-t-30 card-box&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;form-horizontal m-t-10&quot;]/div[@class=&quot;form-group text-center m-t-20 m-b-0&quot;]/div[@class=&quot;col-xs-4 pull-right&quot;]/input[@class=&quot;btn btn-bordred btn-block waves-effect waves-light text-uppercase document-button&quot;]</value>
      <webElementGuid>cc970ed6-01e8-4db0-bef5-99a89dc620fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='submit'])[2]</value>
      <webElementGuid>501f8e49-a564-4517-93fb-67bc2a7ef49c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='stab']/div/div[2]/div/div/form/div/div[2]/div/div[4]/div/input</value>
      <webElementGuid>5183fe8f-1b34-405f-9457-d0d5c2f1069d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[4]/div/input</value>
      <webElementGuid>c988a046-d956-4cb9-b5f8-d2d9e15098b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'submit']</value>
      <webElementGuid>360a6742-e0ab-492c-9ed9-e37430fd0da4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
