<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__email_id</name>
   <tag></tag>
   <elementGuidId>aefe4c1e-0b0c-4660-bc34-5abe9f825aa4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_email_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_email_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Enter Email Id&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6905a9c8-9c11-4d8a-9398-a749dbc5764c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c1cc0f50-5493-4d08-acb2-36dc9194f053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email_id</value>
      <webElementGuid>55043305-b3b0-44de-851b-72cda8207ff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-sm</value>
      <webElementGuid>d3e18ef6-08f8-493d-9aa5-6c70d94d6066</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Email Id</value>
      <webElementGuid>ae1b068b-a495-4de3-919c-8d66ed0c6706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>b1e31725-f8bd-4b3b-bb49-fff70e4eea23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_email_id</value>
      <webElementGuid>632451ec-7b96-49e8-8561-a2ea7c9008cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;stab&quot;)/div[@class=&quot;resp-tabs-container hor_1&quot;]/div[@class=&quot;search_view resp-tab-content hor_1 resp-tab-content-active&quot;]/form[@class=&quot;pagination_list&quot;]/div[@class=&quot;w3_regular_search&quot;]/div[@class=&quot;form_but1&quot;]/div[@class=&quot;col-sm-7 form_radios&quot;]/input[@id=&quot;id_email_id&quot;]</value>
      <webElementGuid>708116e6-ba7b-4298-8da6-1cbff958e3de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_email_id']</value>
      <webElementGuid>0aebba52-c147-43e4-8230-9bb2eec0458a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='stab']/div/div/form/div/div[5]/div/input</value>
      <webElementGuid>0a7daff5-2df2-4055-8dae-fa92c86f7a16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>9b0cdd5b-a346-4b6c-8e2a-0fbaa404ea03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'email_id' and @placeholder = 'Enter Email Id' and @id = 'id_email_id']</value>
      <webElementGuid>321de2aa-7e48-4458-86f8-88d60d582c59</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
