<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Pensioner Login_pensioner_id</name>
   <tag></tag>
   <elementGuidId>31c9da90-5743-4b5c-8ef7-199db30deb13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_pensioner_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_pensioner_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Enter Pensioner Number&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1fe03e05-31d1-4a37-bc77-aeee99ccfed9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7600d17b-f2e8-4055-a74e-566f7708f42f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pensioner_id</value>
      <webElementGuid>720fe943-edb1-430d-aa64-86df646070ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>5c496804-6956-4778-bc17-ff25bae3aa0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Pensioner Number</value>
      <webElementGuid>6bf0d1aa-b635-47b7-921e-e6451ac24c97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_pensioner_id</value>
      <webElementGuid>5eb3558b-2e30-4643-af2b-7ce12bf41666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_pensioner_id&quot;)</value>
      <webElementGuid>21a4136e-9355-4ce8-a96d-57aac559aceb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_pensioner_id']</value>
      <webElementGuid>d7719b0e-3075-4a56-ad97-9c83d79ea44a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>a0bc5461-47d2-4423-a7ad-a489771de590</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'pensioner_id' and @placeholder = 'Enter Pensioner Number' and @id = 'id_pensioner_id']</value>
      <webElementGuid>50e77af7-2e7c-407c-82f6-f357c62bef39</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
