<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__aadhaar_no</name>
   <tag></tag>
   <elementGuidId>46589371-1a53-422c-ad96-fe474f1bf607</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_aadhaar_no</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_aadhaar_no']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Enter Aadhaar  No&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>822690e4-259c-4672-a772-1d488d6f88e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1f34c643-4e64-49db-9e21-74754871051b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>aadhaar_no</value>
      <webElementGuid>afc04dba-8693-49e0-9c1a-f7ed58e3dbb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-sm numbers</value>
      <webElementGuid>44312ec3-b387-4137-a204-a2c89e754a27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Aadhaar  No</value>
      <webElementGuid>61a7af11-7158-43a8-bf8c-1a748c04ea18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>38f14d9b-d445-4eb6-9ad5-4d3961996989</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_aadhaar_no</value>
      <webElementGuid>3b76f2ea-5370-4993-a5ed-5a196cea12f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_aadhaar_no&quot;)</value>
      <webElementGuid>5a475a7e-8c20-45ce-acbb-d97d0e315852</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_aadhaar_no']</value>
      <webElementGuid>67a6d179-c7d2-4971-8226-4f0c942c1d9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='stab']/div/div/form/div/div[4]/div/input</value>
      <webElementGuid>089a0eba-db8c-407a-9d95-2ec455569508</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>368c2992-5fe3-4989-a1f3-e109f05d626a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'aadhaar_no' and @placeholder = 'Enter Aadhaar  No' and @id = 'id_aadhaar_no']</value>
      <webElementGuid>5c117ea4-401f-496a-a998-208c44cfbeaa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
