<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Employee Login_emp_id</name>
   <tag></tag>
   <elementGuidId>57519279-1b56-4e54-8216-072b279c81b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_emp_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_emp_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Enter Employee Id&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>486a9415-f3f1-4c65-b729-d8def9c308dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>40dd8eaa-3595-4090-97df-8c06d49ac4b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>emp_id</value>
      <webElementGuid>c5572cc7-74fc-48f5-beaa-ae1043c9394f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e274e3cd-6f84-4b1a-9d04-fe780153f74e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Employee Id</value>
      <webElementGuid>1d15444b-33c1-45c7-8a2e-6d6f9d00dad6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_emp_id</value>
      <webElementGuid>d235ca99-1adf-4b18-b675-a6a1cbf0a985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_emp_id&quot;)</value>
      <webElementGuid>8d2390c6-7fd0-4bce-b756-e3b3d2e20b31</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_emp_id']</value>
      <webElementGuid>4f86c4f9-2ec5-4fb5-b27a-9663d4964436</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>e8d9761e-cf6b-4d00-a7f3-110eea1d2afe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'emp_id' and @placeholder = 'Enter Employee Id' and @id = 'id_emp_id']</value>
      <webElementGuid>e26f6697-17a7-4c07-81fd-140d62d74b56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
