<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Employee Login_pan_no</name>
   <tag></tag>
   <elementGuidId>57854c66-207f-4e50-8efe-ac5765b26d7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_pan_no</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_pan_no']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Enter PAN Number&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>741391f6-fc7b-4961-9247-82c831ae3c5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bb531b90-201f-4c5c-a8cc-85872673d2c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pan_no</value>
      <webElementGuid>4f544ad3-2aff-43db-ba8c-6c318d206708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9735ed35-cd35-4189-b8b4-0bf588ab9bd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter PAN Number</value>
      <webElementGuid>b5bfe2fc-d8bd-4210-b909-eb6a654d346f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_pan_no</value>
      <webElementGuid>61bb0efb-57e0-4f07-ade9-aa0dcd4f7d66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_pan_no&quot;)</value>
      <webElementGuid>163ea19c-6d90-4e2a-8f94-791f71ef5e01</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_pan_no']</value>
      <webElementGuid>d0e55414-eddb-4075-ad4b-f8a658279abe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>29442e6d-dd50-4d4e-9642-b3309dbf9913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'pan_no' and @placeholder = 'Enter PAN Number' and @id = 'id_pan_no']</value>
      <webElementGuid>db2c163a-6e74-4438-a9be-dd980b8362c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
