<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__login_confirm_password</name>
   <tag></tag>
   <elementGuidId>58feb47d-a576-4ba6-a99c-d98c4a2126dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_login_confirm_password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_login_confirm_password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Enter Confirm Password&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>037f4752-c602-41b3-83c8-7e1f28519e97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>3fe863b9-8cdd-45a0-a060-ed52337ec0e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>login_confirm_password</value>
      <webElementGuid>4b687761-2c65-4d59-b9d9-874964c3ebe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control-50 input-sm</value>
      <webElementGuid>ddeb3764-5422-4dc5-a1f0-fc71d887825c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Confirm Password</value>
      <webElementGuid>3aa3e28d-6d0e-4833-83bb-6dd4933fcd6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>9ceece7f-ea74-41e5-ad90-61bee4bce9b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_login_confirm_password</value>
      <webElementGuid>39f0c807-9974-4ffe-9a32-98e793b0a095</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_login_confirm_password&quot;)</value>
      <webElementGuid>8b9bc224-3cd3-4b34-a9ae-0e637c3ef9dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_login_confirm_password']</value>
      <webElementGuid>255aede2-aee5-414c-ad99-099f1ab4ceb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='stab']/div/div/form/div/div[7]/div/input</value>
      <webElementGuid>08bf246b-62c1-46d7-a9ee-cfe1696f02b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/input</value>
      <webElementGuid>1ea1fa19-8d73-4d2c-b61e-466077830f6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'login_confirm_password' and @placeholder = 'Enter Confirm Password' and @id = 'id_login_confirm_password']</value>
      <webElementGuid>045d647c-114e-43e8-b884-beb04fe6c22c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
