<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Show Password_chk_password</name>
   <tag></tag>
   <elementGuidId>79a4f516-8559-4f1e-beb2-cd14bdb2f314</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#chk_password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='chk_password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#chk_password</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8fb16580-d658-40c7-b854-2db779bdb14a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>24ae8d7d-0cd8-466b-adc6-bf6035f2c9ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chk_password</value>
      <webElementGuid>354d8627-3566-4dc3-bcd5-1167bc898504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chk_password&quot;)</value>
      <webElementGuid>ea5b73ae-63b5-4580-8f1d-054341e59e27</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='chk_password']</value>
      <webElementGuid>9b08d002-800f-43aa-b5b7-e163718af07f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>2939ea28-d90d-4c91-8c54-5172f8f46328</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'chk_password']</value>
      <webElementGuid>8a2d6a65-7d25-496a-94ea-f1782ee093e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
